# Generated by Django 4.0.4 on 2022-05-18 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_post_author_name_alter_post_post_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='pub_date',
            field=models.DateTimeField(default=None, verbose_name='Дата публикации'),
        ),
    ]
