# Generated by Django 4.0.4 on 2022-05-23 14:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(max_length=40, verbose_name='Автора вопроса')),
                ('question_title', models.CharField(max_length=40, verbose_name='Загаловок вопроса')),
                ('question_text', models.TextField(verbose_name='Текст вопроса')),
                ('question_category', models.CharField(max_length=40, verbose_name='Катигория')),
                ('pub_date', models.DateTimeField(verbose_name='Дата публикации')),
            ],
            options={
                'verbose_name': 'Question',
                'verbose_name_plural': 'Questions',
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(max_length=40, verbose_name='Автор коментария')),
                ('comment_text', models.CharField(max_length=100, verbose_name='Текст коментария')),
                ('pub_date', models.DateTimeField(verbose_name='Дата публикации')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forums.question')),
            ],
        ),
    ]
