# Generated by Django 4.0.4 on 2022-05-27 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forums', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='author',
            field=models.CharField(default='None', max_length=50, verbose_name='Логин автора'),
        ),
        migrations.AddField(
            model_name='question',
            name='author',
            field=models.CharField(default='None', max_length=50, verbose_name='Логин автора'),
        ),
    ]
